-- Generated chunk for spellcheck dictionary
local _, YapperTable = ...
local mainY = _G.Yapper or Yapper
if (not YapperTable or not YapperTable.Spellcheck) and mainY and mainY.Spellcheck then
    YapperTable = YapperTable or {}
    YapperTable.Spellcheck = mainY.Spellcheck
end
if not YapperTable or not YapperTable.Spellcheck then return end
YapperTable.Spellcheck:RegisterDictionary("esES", {
    words = {
        "ómnibuses",
        "ónice",
        "ónices",
        "ónique",
        "óniques",
        "ópalo",
        "ópalos",
        "ópera",
        "óperas",
        "óptico",
        "ópticos",
        "óptimo",
        "óptimos",
        "órbita",
        "órbitas",
        "órdenes",
        "órgano",
        "órganos",
        "órsay",
        "óscar",
        "ósculo",
        "ósculos",
        "óseo",
        "óseos",
        "ósmosis",
        "óvalo",
        "óvalos",
        "óvulo",
        "óvulos",
        "óxido",
        "óxidos",
        "óyela",
        "óyelas",
        "óyele",
        "óyeles",
        "óyelo",
        "óyelos",
        "óyeme",
        "óyenos",
        "úbeda",
        "úes",
        "úlcera",
        "úlceras",
        "últimamente",
        "último",
        "últimos",
        "únala",
        "únalas",
        "únale",
        "únales",
        "únalo",
        "únalos",
        "únanla",
        "únanlas",
        "únanle",
        "únanles",
        "únanlo",
        "únanlos",
        "únanse",
        "únase",
        "únete",
        "únicamente",
        "único",
        "únicos",
        "úntala",
        "úntalas",
        "úntale",
        "úntales",
        "úntalo",
        "úntalos",
        "úntate",
        "úntela",
        "úntelas",
        "úntelo",
        "úntelos",
        "úntenla",
        "úntenlas",
        "úntenle",
        "úntenles",
        "úntenlo",
        "úntenlos",
        "úntense",
        "úntese",
        "úrico",
        "úricos",
        "úsala",
        "úsalas",
        "úsale",
        "úsales",
        "úsalo",
        "úsalos",
        "úsame",
        "úsanos",
        "úsela",
        "úselas",
        "úsele",
        "úseles",
        "úselo",
        "úselos",
        "úseme",
        "úsenla",
        "úsenlas",
        "úsenle",
        "úsenles",
        "úsenlo",
        "úsenlos",
        "úsenme",
        "úsennos",
        "úsenos",
        "úsense",
        "úsese",
        "útero",
        "úteros",
        "útil",
        "útiles",
        "útilmente",
        "úvea",
        "úveas",
        "úvula",
        "úvulas",
    }
})

-- YAPPER_LOD_PRINT
if DEFAULT_CHAT_FRAME and DEFAULT_CHAT_FRAME.AddMessage then
    DEFAULT_CHAT_FRAME:AddMessage("Yapper: loaded esES dictionary")
end
