-- Yapper_Dict_en/Engine.lua
-- English language engine for the Yapper Spellcheck system.
--
-- Registers via YapperAPI:RegisterLanguageEngine("en", engine).
-- This must load before Dict_enBase.lua (ensured by TOC order).
--
-- IMPORTANT: The phonetic rules in GetPhoneticHash MUST remain in exact parity
-- with the Python generation script (tools/generate_phonetic_dict_en.py).
-- See Documentation/Spellcheck/SpellcheckSpec.md for the change protocol.

-- ---------------------------------------------------------------------------
-- Variant rules: spellings that differ between English dialects.
-- Used by the scoring engine to boost candidates that are variant-spellings
-- of the input (e.g. "colour" suggested when the user types "color").
-- ---------------------------------------------------------------------------
local VARIANT_RULES = {
    { "or",   "our"  }, { "our",  "or"   },
    { "ize",  "ise"  }, { "ise",  "ize"  },
    { "er",   "re"   }, { "re",   "er"   },
    { "og",   "ogue" }, { "ogue", "og"   },
    { "l",    "ll"   }, { "ll",   "l"    },
}

--- 32-bit DJB2 Hash matching the Python generator script.
local string_byte = string.byte
local function HashWord(word)
    local hash = 5381
    for i = 1, #word do
        -- Modulo 2^32 to ensure it fits in 32-bit unsigned bounds
        hash = ((hash * 33) + string_byte(word, i)) % 4294967296
    end
    return hash
end

-- ---------------------------------------------------------------------------
-- Blocked words hashes (DJB2)
-- Generated by tools/generate_blocklist.py
-- Word lists used: https://github.com/BurntRouter/filtered-word-lists
-- ---------------------------------------------------------------------------
local BLOCKED_HASHES = {
    [1924744940] = true, [4102830604] = true, [1269130561] = true, [3387041453] = true, 
    [192264344] = true, [2090159296] = true, [3387045665] = true, [255780147] = true, 
    [456405453] = true, [2090436841] = true, [2588573972] = true, [193511757] = true, 
    [330654977] = true, [3600988070] = true, [1375641903] = true, [3425416807] = true,
    [270321543] = true, [3234139055] = true, [3154119218] = true, [2146852374] = true, 
    [1685567371] = true, [422016536] = true, [3548927835] = true, [343708735] = true, 
    [2230350614] = true, [302278623] = true, [3800387947] = true, [1187451698] = true, 
    [270320894] = true, [2811021064] = true, [271290180] = true, [2090401420] = true, 
    [2090185024] = true, [2601496658] = true, [1355260557] = true, [193488488] = true, 
    [261605702] = true, [2090162493] = true, [1849507365] = true, [3035773747] = true, 
    [3242242805] = true, [2090687707] = true, [274682737] = true, [2090544516] = true, 
    [2090156020] = true, [265589651] = true, [3367631986] = true, [3137705472] = true, 
    [2090607818] = true, [193489663] = true, [2090324377] = true, [1194647656] = true, 
    [3872614978] = true, [3275079834] = true, [2090623140] = true, [4181050045] = true, 
    [193487068] = true, [1072297390] = true, [260415624] = true, [42880227] = true, 
    [268507197] = true, [35542499569] = true, [1809970073] = true, [2090155621] = true, 
    [2090874501] = true, [1415043910] = true, [254486106] = true, [1000590745] = true, 
    [2090623300] = true, [3647373826] = true, [193485975] = true, [3232008580] = true, 
    [2090729038] = true, [3370049694] = true, [169341747] = true, [258717741] = true, 
    [2090544831] = true, [4243675682] = true, [193512331] = true, [4101663913] = true, 
    [355929612] = true, [3894441888] = true, [3542813698] = true, [2090428531] = true, 
    [1932286739] = true, [1611502285] = true, [258718006] = true, [270321025] = true, 
    [4242718141] = true, [320123630] = true, [270000045] = true, [2090508749] = true, 
    [3138248074] = true, [1695921813] = true, [700377911] = true, [2090366967] = true, 
    [42880227] = true, [3172445978] = true, [1685567371] = true, [348734042] = true, 
    [265514124] = true, [275322813] = true, [270328967] = true, [422016536] = true, 
    [2586853629] = true, [261605702] = true, [222163680] = true, [268507197] = true, 
    [464898086] = true, [3542813683] = true, [878419609] = true, [271290180] = true, 
    [2090401420] = true, [1974145175] = true, [3529371519] = true, [2090185024] = true, 
    [2195282430] = true, [2733380898] = true, [1809590071] = true, [356110598] = true, 
    [2090407180] = true, [193495744] = true, [475982537] = true, [521535314] = true, 
    [2090615773] = true, [2090626468] = true, [253141383] = true, [4102830604] = true, 
    [54298430] = true, [355929612] = true, [2090607818] = true, [2090324377] = true, 
    [890994144] = true, [2601496658] = true, [1809970073] = true, [3232008580] = true, 
    [677554903] = true, [2090162527] = true, [260415624] = true, [193487068] = true, 
    [1924744940] = true, [3287784] = true, [163388255] = true, [2090299765] = true, 
    [2090155621] = true, [1611502285] = true, [622539562] = true, [900387225] = true, 
    [193511757] = true, [2018666723] = true, [944344450] = true, [252821814] = true, 
    [3242242805] = true, [4181050045] = true, [3542499569] = true, [1072297390] = true, 
    [2695749341] = true, [1922009142] = true, [711924336] = true, [2090623140] = true, 
    [170853005] = true, [1343182018] = true, [3600987818] = true, [2868485791] = true,
    [4103075241] = true, [677967707] = true, [193487485] = true, [2090508749] = true, 
    [4102779131] = true, [2090544516] = true, [2929363216] = true, [2090428531] = true, 
    [272958513] = true, [4223370912] = true, [2090729038] = true, [3387041453] = true, 
    [1066225748] = true, [2446782854] = true, [469348250] = true, [816127422] = true, 
    [2634516259] = true, [1208899288] = true, [2230350614] = true, [417701304] = true, 
    [323104056] = true, [193489663] = true, [1194647656] = true, [910659274] = true, 
    [3649346240] = true, [763136093] = true, [3881902284] = true, [2271568594] = true, 
    [193506902] = true, [270868743] = true, [456405453] = true, [3071101625] = true, 
    [270326472] = true, [2090830197] = true, [330654662] = true, [136969805] = true, 
    [193488488] = true, [689281295] = true, [1359747939] = true, [948739336] = true, 
    [3198697029] = true, [261604917] = true, [4142207584] = true, [4243675326] = true, 
    [302278623] = true, [1343869934] = true, [1932286739] = true, [3894441888] = true, 
    [4245011667] = true, [4101663913] = true, [3881983355] = true, [3137705472] = true, 
    [1000590745] = true, [3781555528] = true, [3548927835] = true, [3551229124] = true, 
    [192264344] = true, [2570745296] = true, [3542806075] = true, [5863608] = true, 
    [3397886225] = true, [267302460] = true, [1929455806] = true, [461897986] = true, 
    [1406798931] = true, [42880769] = true, [2811021064] = true, [164091049] = true, 
    [1187451698] = true, [3870490900] = true, [1161776932] = true, [279139018] = true, 
    [7126123] = true, [3367631986] = true, [3050186175] = true, [193502837] = true, 
    [2090508457] = true, [3548723903] = true, [3275079834] = true, [258717741] = true, 
    [2090185387] = true, [5863642] = true, [3978900503] = true, [2090162493] = true, 
    [661442904] = true, [320123630] = true, [994245990] = true, [255413938] = true, 
    [193513432] = true, [3548864211] = true, [268492604] = true, [2090760585] = true, 
    [260776244] = true, [3370049694] = true, [2823968682] = true, [43053689] = true, 
    [193500364] = true, [282574809] = true, [2090401176] = true, [4103074299] = true, 
    [3353007943] = true, [2375203291] = true, [677967961] = true, [1041643915] = true, 
    [3695606242] = true, [255780147] = true, [3639517203] = true, [355880415] = true, 
    [270843888] = true, [573919259] = true, [4133685000] = true, [2090717488] = true, 
    [1639967491] = true, [3542813698] = true, [470670047] = true, [1637634698] = true, 
    [193497158] = true, [3484277290] = true, [169341747] = true, [3872614978] = true, 
    [2090775205] = true, [113305079] = true, [474595844] = true, [1098595893] = true, 
    [1269130561] = true, [4243675682] = true, [7256661] = true, [4242718141] = true, 
    [2090773579] = true, [2454697371] = true, [3437049465] = true, [352779459] = true, 
    [2090069994] = true, [3800487335] = true, [263960319] = true, [260616774] = true, 
    [628095536] = true, [256858114] = true, [43104448] = true, [3154119218] = true, 
    [2090590278] = true, [1921832466] = true, [193488578] = true, [2090616624] = true, 
    [1355260557] = true, [270581373] = true, [1809590086] = true, [3387045665] = true, 
    [193496018] = true, [3906997489] = true, [2596850495] = true, [3035773747] = true, 
    [3600985787] = true, [3600988219] = true, [170868384] = true, [3425414761] = true,
    [2446509878] = true,
    [436922091] = true, [465340996] = true, [2090679853] = true, [352565713] = true, 
    [583188959] = true, [1639246084] = true, [465065587] = true, [427081359] = true, 
    [330921434] = true, [535698116] = true, [2090472517] = true, [2257510488] = true, 
    [4245015879] = true, [2891210747] = true, [3116217937] = true, [251629441] = true, 
    [270728388] = true, [3155742719] = true, [4291790405] = true, [4282513142] = true, 
    [54701204] = true, [2090120071] = true, [2090544831] = true, [2321679764] = true, 
    [4164846805] = true, [422579975] = true, [174513116] = true, [193491379] = true, 
    [3799897823] = true, [4103074317] = true, [279171510] = true, [2090156020] = true, 
    [193485975] = true, [3647373826] = true, [2587984460] = true, [2570738552] = true, 
    [2588573972] = true, [3267619070] = true, [991208] = true, [255672039] = true, 
    [3611379852] = true, [270000045] = true, [255557892] = true, [193502737] = true, 
    [270320893] = true, [25916888] = true, [167368054] = true, [274523719] = true, 
    [269464342] = true, [677478740] = true, [343708735] = true, [3800387947] = true, 
    [621439679] = true, [3242951102] = true, [275462634] = true, [1120037436] = true, 
    [898106660] = true, [3847041754] = true, [2090159296] = true, [420887339] = true, 
    [3006619808] = true, [3127763176] = true, [254484731] = true, [1159902974] = true, 
    [920740902] = true, [2090859478] = true, [270871971] = true, [271309145] = true, 
    [235162174] = true, [258718006] = true, [1871073353] = true, [2249423871] = true, 
    [270321025] = true, [271309141] = true, [257060302] = true, [84915573] = true, 
    [2090443117] = true, [174523661] = true, [4149252206] = true, [261958657] = true, 
    [4011873711] = true, [160279187] = true, [1834861496] = true, [274675815] = true, 
    [3568900211] = true, [1913286855] = true, [672146765] = true, [270320894] = true, 
    [2090874501] = true, [1041902069] = true, [1415043910] = true, [3234139055] = true, 
    [3222627334] = true, [465341128] = true, [2090436841] = true, [23030024] = true, 
    [270321543] = true, [551146238] = true, [469853051] = true, [2090772550] = true, 
    [2372888660] = true, [4090711922] = true, [3542806060] = true, [271309161] = true, 
    [5863241] = true, [1483415783] = true, [2259595891] = true, [261600462] = true, 
    [758791902] = true, [274284925] = true, [254485722] = true, [3856054570] = true, 
    [2090623300] = true, [2090939742] = true, [193505685] = true, [1534198020] = true, 
    [267014964] = true, [4153563690] = true, [1648746202] = true, [3762814904] = true, 
    [254486106] = true, [1773925536] = true, [2090976075] = true, [421989845] = true, 
    [2090859474] = true, [265589651] = true, [1849507365] = true, [278417139] = true, 
    [80697020] = true, [193512331] = true, [274682737] = true, [4174111140] = true, 
    [2132045460] = true, [2146852374] = true, [1007956785] = true, [3434422957] = true, 
    [2140386772] = true, [1501483892] = true, [193499175] = true, 
}

-- ---------------------------------------------------------------------------
-- Keyboard layouts
-- Each layout maps lowercase letter → {x, y} screen coordinates.
-- x is the column (with stagger offset), y is the row.
-- Only a-z; digits and punctuation are filtered before proximity scoring.
-- ---------------------------------------------------------------------------
local KB_LAYOUTS = {
    QWERTY = {
        q = { 0,    0 }, w = { 1,    0 }, e = { 2,    0 }, r = { 3,    0 },
        t = { 4,    0 }, y = { 5,    0 }, u = { 6,    0 }, i = { 7,    0 },
        o = { 8,    0 }, p = { 9,    0 },
        a = { 0.25, 1 }, s = { 1.25, 1 }, d = { 2.25, 1 }, f = { 3.25, 1 },
        g = { 4.25, 1 }, h = { 5.25, 1 }, j = { 6.25, 1 }, k = { 7.25, 1 },
        l = { 8.25, 1 },
        z = { 0.75, 2 }, x = { 1.75, 2 }, c = { 2.75, 2 }, v = { 3.75, 2 },
        b = { 4.75, 2 }, n = { 5.75, 2 }, m = { 6.75, 2 },
    },
    QWERTZ = {
        q = { 0,    0 }, w = { 1,    0 }, e = { 2,    0 }, r = { 3,    0 },
        t = { 4,    0 }, z = { 5,    0 }, u = { 6,    0 }, i = { 7,    0 },
        o = { 8,    0 }, p = { 9,    0 },
        a = { 0.25, 1 }, s = { 1.25, 1 }, d = { 2.25, 1 }, f = { 3.25, 1 },
        g = { 4.25, 1 }, h = { 5.25, 1 }, j = { 6.25, 1 }, k = { 7.25, 1 },
        l = { 8.25, 1 },
        y = { 0.75, 2 }, x = { 1.75, 2 }, c = { 2.75, 2 }, v = { 3.75, 2 },
        b = { 4.75, 2 }, n = { 5.75, 2 }, m = { 6.75, 2 },
    },
    AZERTY = {
        a = { 0,    0 }, z = { 1,    0 }, e = { 2,    0 }, r = { 3,    0 },
        t = { 4,    0 }, y = { 5,    0 }, u = { 6,    0 }, i = { 7,    0 },
        o = { 8,    0 }, p = { 9,    0 },
        q = { 0.25, 1 }, s = { 1.25, 1 }, d = { 2.25, 1 }, f = { 3.25, 1 },
        g = { 4.25, 1 }, h = { 5.25, 1 }, j = { 6.25, 1 }, k = { 7.25, 1 },
        l = { 8.25, 1 }, m = { 9.25, 1 },
        w = { 0.75, 2 }, x = { 1.75, 2 }, c = { 2.75, 2 }, v = { 3.75, 2 },
        b = { 4.75, 2 }, n = { 5.75, 2 },
    },
}

-- ---------------------------------------------------------------------------
-- NormaliseVowels
-- Strips vowels (replaced with '*') for vowel-neutral similarity comparisons.
-- ---------------------------------------------------------------------------
local string_gsub  = string.gsub
local string_lower = string.lower
local string_upper = string.upper
local string_sub   = string.sub

local function NormaliseVowels(word)
    if type(word) ~= "string" then return "" end
    return string_gsub(string_lower(word), "[aeiouy]", "*")
end

-- ---------------------------------------------------------------------------
-- GetPhoneticHash  (MUST match tools/generate_phonetic_dict_en.py exactly)
--
-- Change protocol (see SpellcheckSpec.md):
--   1. Update SpellcheckSpec.md → English phonetic rules section
--   2. Update this function
--   3. Update tools/generate_phonetic_dict_en.py
--   4. Regenerate enBase, enGB, enUS phonetics tables
-- ---------------------------------------------------------------------------
local function GetPhoneticHash(word)
    local hash = string_upper(word)
    -- Strip non-alphabetic characters (including apostrophes)
    hash = string_gsub(hash, "[^%a]", "")

    -- Strip duplicate adjacent letters (e.g. "LL" → "L")
    hash = string_gsub(hash, "(%a)%1", "%1")

    -- Silent / variable consonant groups
    hash = string_gsub(hash, "GHT", "T")
    hash = string_gsub(hash, "PH",  "F")
    hash = string_gsub(hash, "KN",  "N")
    hash = string_gsub(hash, "GN",  "N")
    hash = string_gsub(hash, "WR",  "R")
    hash = string_gsub(hash, "CH",  "K")
    hash = string_gsub(hash, "SH",  "X")
    hash = string_gsub(hash, "C",   "K")
    hash = string_gsub(hash, "Q",   "K")
    hash = string_gsub(hash, "X",   "KS")
    hash = string_gsub(hash, "Z",   "S")

    -- GH at end of word sounds like F (laugh, enough)
    if string_sub(hash, -2) == "GH" then
        hash = string_sub(hash, 1, -3) .. "F"
    else
        hash = string_gsub(hash, "GH", "")  -- silent GH (night, through)
    end

    if hash == "" then return "" end

    -- Keep first letter; strip remaining vowels
    local firstChar = string_sub(hash, 1, 1)
    local rest      = string_sub(hash, 2)
    rest = string_gsub(rest, "[AEIOUY]", "")

    return firstChar .. rest
end

-- ---------------------------------------------------------------------------
-- Register the English language engine with Yapper.
-- YapperAPI is a global injected by Yapper before any LOD addons load.
-- ---------------------------------------------------------------------------
if not _G.YapperAPI then
    -- Safety net: if this somehow loads before Yapper, bail gracefully.
    return
end

local ok = YapperAPI:RegisterLanguageEngine("en", {
    -- Required
    GetPhoneticHash = GetPhoneticHash,

    -- Optional helpers — fall back to built-in if absent
    NormaliseVowels = NormaliseVowels,

    -- English has British/American spelling variants
    HasVariantRules = true,
    VariantRules    = VARIANT_RULES,

    -- Keyboard layout data (same schema as the built-in KB_LAYOUTS table)
    KBLayouts       = KB_LAYOUTS,

    -- Blocked words hashes and the corresponding hash function
    BlockedHashes   = BLOCKED_HASHES,
    HashWord        = HashWord,

    -- No ScoreWeights override — English uses the built-in defaults
    ScoreWeights    = nil,
})

if not ok then
    -- This should never happen unless Yapper is out of date.
    if DEFAULT_CHAT_FRAME then
        DEFAULT_CHAT_FRAME:AddMessage(
            "|cffff6666Yapper_Dict_en:|r Failed to register English language engine. " ..
            "Ensure Yapper is up to date."
        )
    end
end
