-- Yapper_Dict_en/Engine.lua
-- English language engine for the Yapper Spellcheck system.
--
-- Registers via YapperAPI:RegisterLanguageEngine("en", engine).
-- This must load before Dict_enBase.lua (ensured by TOC order).
--
-- IMPORTANT: The phonetic rules in GetPhoneticHash MUST remain in exact parity
-- with the Python generation script (tools/generate_phonetic_dict_en.py).
-- See Documentation/Spellcheck/SpellcheckSpec.md for the change protocol.

-- ---------------------------------------------------------------------------
-- Variant rules: spellings that differ between English dialects.
-- Used by the scoring engine to boost candidates that are variant-spellings
-- of the input (e.g. "colour" suggested when the user types "color").
-- ---------------------------------------------------------------------------
local VARIANT_RULES = {
    { "or",   "our"  }, { "our",  "or"   },
    { "ize",  "ise"  }, { "ise",  "ize"  },
    { "er",   "re"   }, { "re",   "er"   },
    { "og",   "ogue" }, { "ogue", "og"   },
    { "l",    "ll"   }, { "ll",   "l"    },
}

--- 32-bit DJB2 Hash matching the Python generator script.
local string_byte = string.byte
local function HashWord(word)
    local hash = 5381
    for i = 1, #word do
        -- Modulo 2^32 to ensure it fits in 32-bit unsigned bounds
        hash = ((hash * 33) + string_byte(word, i)) % 4294967296
    end
    return hash
end

-- ---------------------------------------------------------------------------
-- Blocked words hashes (DJB2)
-- Generated by tools/generate_blocklist.py
-- Word lists used: https://github.com/BurntRouter/filtered-word-lists
-- ---------------------------------------------------------------------------
local BLOCKED_HASHES = {
    [622539562] = true, [3242951102] = true, [613308109] = true, 
    [266134777] = true, [1695921813] = true, [270328967] = true, 
    [461897986] = true, [3529371519] = true, [5863241] = true, 
    [2090717488] = true, [2090508749] = true, [2831621462] = true, 
    [255658872] = true, [1924744940] = true, [251629441] = true, 
    [2090760585] = true, [1924744954] = true, [2090729038] = true, 
    [948487777] = true, [2090082593] = true, [2724582931] = true, 
    [279139018] = true, [2090428531] = true, [193499175] = true, 
    [2601496658] = true, [4243675326] = true, [3870490900] = true, 
    [271092275] = true, [193497158] = true, [3781555528] = true, 
    [4011873513] = true, [3370049694] = true, [2090472517] = true, 
    [2090120071] = true, [2090401176] = true, [3434422957] = true, 
    [3881902284] = true, [274284925] = true, [4090711922] = true, 
    [2570738763] = true, [2257510488] = true, [2090544516] = true, 
    [274634823] = true, [268420664] = true, [3695602030] = true, 
    [1862480475] = true, [2090152561] = true, [1631760709] = true, 
    [2372888660] = true, [7256661] = true, [363267836] = true, 
    [3137705472] = true, [470670047] = true, [2634516259] = true, 
    [672146765] = true, [3908947801] = true, [1031526798] = true, 
    [1639967491] = true, [3978900503] = true, [323104056] = true, 
    [160279187] = true, [2132045460] = true, [4153563690] = true, 
    [193511757] = true, [274388866] = true, [2454697357] = true, 
    [3548723903] = true, [3387041453] = true, [272958513] = true, 
    [920740902] = true, [521535314] = true, [4266297088] = true, 
    [193488578] = true, [275462634] = true, [456405453] = true, 
    [4149252206] = true, [2090679853] = true, [3387045665] = true, 
    [1483415783] = true, [843928860] = true, [274689238] = true, 
    [276126727] = true, [5863642] = true, [193487068] = true, 
    [3762899846] = true, [2090536439] = true, [3881983355] = true, 
    [1974145313] = true, [4243178919] = true, [3348842270] = true, 
    [689281295] = true, [3172445978] = true, [256638737] = true, 
    [3437049465] = true, [816127422] = true, [2601496672] = true, 
    [1161776932] = true, [4282513142] = true, [3542807164] = true, 
    [270321025] = true, [3348846476] = true, [1913286855] = true, 
    [2090269966] = true, [3367631986] = true, [4242727017] = true, 
    [2090262720] = true, [193489271] = true, [167368054] = true, 
    [356110598] = true, [473014688] = true, [1015824151] = true, 
    [3186195766] = true, [193506902] = true, [193488778] = true, 
    [3800487335] = true, [258718006] = true, [505614840] = true, 
    [3138248074] = true, [270326472] = true, [271290180] = true, 
    [164091049] = true, [255420136] = true, [3881902324] = true, 
    [3799897823] = true, [2090443117] = true, [464898086] = true, 
    [4242718141] = true, [4181548765] = true, [268492594] = true, 
    [3222627334] = true, [417701304] = true, [279171510] = true, 
    [222163680] = true, [4181050045] = true, [255420036] = true, 
    [1809590086] = true, [3059298528] = true, [4109894657] = true, 
    [254484731] = true, [2587984460] = true, [2090590278] = true, 
    [3131237710] = true, [518647874] = true, [2230350614] = true, 
    [2446782854] = true, [2891212625] = true, [2588573972] = true, 
    [2090615773] = true, [3348861570] = true, [2090629297] = true, 
    [489115782] = true, [1809590071] = true, [1362439070] = true, 
    [2891210747] = true, [2090859474] = true, [3050186175] = true, 
    [890994144] = true, [722281450] = true, [2090401407] = true, 
    [628095536] = true, [4103075241] = true, [3867428740] = true, 
    [255413938] = true, [3800387947] = true, [573919259] = true, 
    [661442904] = true, [255557892] = true, [268492604] = true, 
    [3542806075] = true, [3035773747] = true, [2140386772] = true, 
    [193488182] = true, [465065587] = true, [54298430] = true, 
    [1208899288] = true, [5863608] = true, [256858114] = true, 
    [2090401420] = true, [193488488] = true, [4291790405] = true, 
    [352779459] = true, [3397886225] = true, [1871073353] = true, 
    [3695606242] = true, [193510484] = true, [3568900211] = true, 
    [43104448] = true, [4245011667] = true, [3006619808] = true, 
    [2090156020] = true, [270320893] = true, [347913350] = true, 
    [4245015879] = true, [271309145] = true, [270320901] = true, 
    [3867428754] = true, [259432257] = true, [3762814904] = true, 
    [193500355] = true, [3127763176] = true, [270728388] = true, 
    [2090299765] = true, [3542813683] = true, [4266597535] = true, 
    [2570738552] = true, [1120037436] = true, [277738914] = true, 
    [1187451698] = true, [136969805] = true, [677967707] = true, 
    [898106660] = true, [677478740] = true, [994245990] = true, 
    [2090772550] = true, [274682737] = true, [4174111140] = true, 
    [2090775205] = true, [4011873711] = true, [3348842264] = true, 
    [1534198020] = true, [274545696] = true, [3872614978] = true, 
    [583188959] = true, [2928268063] = true, [4266296823] = true, 
    [253141383] = true, [2090155621] = true, [320123630] = true, 
    [1809970073] = true, [343708735] = true, [2090185024] = true, 
    [261604917] = true, [271309161] = true, [2090773579] = true, 
    [2090623300] = true, [2090248326] = true, [254485722] = true, 
    [270843888] = true, [270320883] = true, [265827870] = true, 
    [3287784] = true, [2586853629] = true, [2090087536] = true, 
    [257060302] = true, [2090727949] = true, [3071101625] = true, 
    [2090162493] = true, [3611379852] = true, [193495744] = true, 
    [1974145175] = true, [1310665196] = true, [2259595891] = true, 
    [3198697029] = true, [3906997489] = true, [1648746202] = true, 
    [3762954223] = true, [193502837] = true, [3542806060] = true, 
    [2271568594] = true, [3924984663] = true, [4266296837] = true, 
    [193491379] = true, [2454697371] = true, [330659348] = true, 
    [193507364] = true, [422579975] = true, [677554903] = true, 
    [473014682] = true, [2090830197] = true, [193505685] = true, 
    [1000590745] = true, [3548927835] = true, [1343869934] = true, 
    [535698116] = true, [3358763847] = true, [193496018] = true, 
    [1611502285] = true, [2090542338] = true, [255886770] = true, 
    [4223370912] = true, [2090626468] = true, [270843616] = true, 
    [271309141] = true, [3249195276] = true, [1538513496] = true, 
    [910659274] = true, [1406798931] = true, [3894441888] = true, 
    [421989845] = true, [268492587] = true, [258717741] = true, 
    [2090859478] = true, [3847041754] = true, [2733380898] = true, 
    [4011873480] = true, [2929363216] = true, [898097966] = true, 
    [270320894] = true, [278886159] = true, [2090162527] = true, 
    [278417139] = true, [1060237402] = true, [763136093] = true, 
    [677967961] = true, [427081359] = true, [4243675682] = true, 
}

-- ---------------------------------------------------------------------------
-- Keyboard layouts
-- Each layout maps lowercase letter → {x, y} screen coordinates.
-- x is the column (with stagger offset), y is the row.
-- Only a-z; digits and punctuation are filtered before proximity scoring.
-- ---------------------------------------------------------------------------
local KB_LAYOUTS = {
    QWERTY = {
        q = { 0,    0 }, w = { 1,    0 }, e = { 2,    0 }, r = { 3,    0 },
        t = { 4,    0 }, y = { 5,    0 }, u = { 6,    0 }, i = { 7,    0 },
        o = { 8,    0 }, p = { 9,    0 },
        a = { 0.25, 1 }, s = { 1.25, 1 }, d = { 2.25, 1 }, f = { 3.25, 1 },
        g = { 4.25, 1 }, h = { 5.25, 1 }, j = { 6.25, 1 }, k = { 7.25, 1 },
        l = { 8.25, 1 },
        z = { 0.75, 2 }, x = { 1.75, 2 }, c = { 2.75, 2 }, v = { 3.75, 2 },
        b = { 4.75, 2 }, n = { 5.75, 2 }, m = { 6.75, 2 },
    },
    QWERTZ = {
        q = { 0,    0 }, w = { 1,    0 }, e = { 2,    0 }, r = { 3,    0 },
        t = { 4,    0 }, z = { 5,    0 }, u = { 6,    0 }, i = { 7,    0 },
        o = { 8,    0 }, p = { 9,    0 },
        a = { 0.25, 1 }, s = { 1.25, 1 }, d = { 2.25, 1 }, f = { 3.25, 1 },
        g = { 4.25, 1 }, h = { 5.25, 1 }, j = { 6.25, 1 }, k = { 7.25, 1 },
        l = { 8.25, 1 },
        y = { 0.75, 2 }, x = { 1.75, 2 }, c = { 2.75, 2 }, v = { 3.75, 2 },
        b = { 4.75, 2 }, n = { 5.75, 2 }, m = { 6.75, 2 },
    },
    AZERTY = {
        a = { 0,    0 }, z = { 1,    0 }, e = { 2,    0 }, r = { 3,    0 },
        t = { 4,    0 }, y = { 5,    0 }, u = { 6,    0 }, i = { 7,    0 },
        o = { 8,    0 }, p = { 9,    0 },
        q = { 0.25, 1 }, s = { 1.25, 1 }, d = { 2.25, 1 }, f = { 3.25, 1 },
        g = { 4.25, 1 }, h = { 5.25, 1 }, j = { 6.25, 1 }, k = { 7.25, 1 },
        l = { 8.25, 1 }, m = { 9.25, 1 },
        w = { 0.75, 2 }, x = { 1.75, 2 }, c = { 2.75, 2 }, v = { 3.75, 2 },
        b = { 4.75, 2 }, n = { 5.75, 2 },
    },
}

-- ---------------------------------------------------------------------------
-- NormaliseVowels
-- Strips vowels (replaced with '*') for vowel-neutral similarity comparisons.
-- ---------------------------------------------------------------------------
local string_gsub  = string.gsub
local string_lower = string.lower
local string_upper = string.upper
local string_sub   = string.sub

local function NormaliseVowels(word)
    if type(word) ~= "string" then return "" end
    return string_gsub(string_lower(word), "[aeiouy]", "*")
end

-- ---------------------------------------------------------------------------
-- GetPhoneticHash  (MUST match tools/generate_phonetic_dict_en.py exactly)
--
-- Change protocol (see SpellcheckSpec.md):
--   1. Update SpellcheckSpec.md → English phonetic rules section
--   2. Update this function
--   3. Update tools/generate_phonetic_dict_en.py
--   4. Regenerate enBase, enGB, enUS phonetics tables
-- ---------------------------------------------------------------------------
local function GetPhoneticHash(word)
    local hash = string_upper(word)
    -- Strip non-alphabetic characters (including apostrophes)
    hash = string_gsub(hash, "[^%a]", "")

    -- Strip duplicate adjacent letters (e.g. "LL" → "L")
    hash = string_gsub(hash, "(%a)%1", "%1")

    -- Silent / variable consonant groups
    hash = string_gsub(hash, "GHT", "T")
    hash = string_gsub(hash, "PH",  "F")
    hash = string_gsub(hash, "KN",  "N")
    hash = string_gsub(hash, "GN",  "N")
    hash = string_gsub(hash, "WR",  "R")
    hash = string_gsub(hash, "CH",  "K")
    hash = string_gsub(hash, "SH",  "X")
    hash = string_gsub(hash, "C",   "K")
    hash = string_gsub(hash, "Q",   "K")
    hash = string_gsub(hash, "X",   "KS")
    hash = string_gsub(hash, "Z",   "S")

    -- GH at end of word sounds like F (laugh, enough)
    if string_sub(hash, -2) == "GH" then
        hash = string_sub(hash, 1, -3) .. "F"
    else
        hash = string_gsub(hash, "GH", "")  -- silent GH (night, through)
    end

    if hash == "" then return "" end

    -- Keep first letter; strip remaining vowels
    local firstChar = string_sub(hash, 1, 1)
    local rest      = string_sub(hash, 2)
    rest = string_gsub(rest, "[AEIOUY]", "")

    return firstChar .. rest
end

-- ---------------------------------------------------------------------------
-- Register the English language engine with Yapper.
-- YapperAPI is a global injected by Yapper before any LOD addons load.
-- ---------------------------------------------------------------------------
if not _G.YapperAPI then
    -- Safety net: if this somehow loads before Yapper, bail gracefully.
    return
end

local ok = YapperAPI:RegisterLanguageEngine("en", {
    -- Required
    GetPhoneticHash = GetPhoneticHash,

    -- Optional helpers — fall back to built-in if absent
    NormaliseVowels = NormaliseVowels,

    -- English has British/American spelling variants
    HasVariantRules = true,
    VariantRules    = VARIANT_RULES,

    -- Keyboard layout data (same schema as the built-in KB_LAYOUTS table)
    KBLayouts       = KB_LAYOUTS,

    -- Blocked words hashes and the corresponding hash function
    BlockedHashes   = BLOCKED_HASHES,
    HashWord        = HashWord,

    -- No ScoreWeights override — English uses the built-in defaults
    ScoreWeights    = nil,
})

if not ok then
    -- This should never happen unless Yapper is out of date.
    if DEFAULT_CHAT_FRAME then
        DEFAULT_CHAT_FRAME:AddMessage(
            "|cffff6666Yapper_Dict_en:|r Failed to register English language engine. " ..
            "Ensure Yapper is up to date."
        )
    end
end
