#!/usr/bin/env python3
import sys
import csv
import argparse
from pathlib import Path

def djb2_hash(word):
    """
    Computes a 32-bit DJB2 hash of the word.
    Matches the exact byte-wise implementation in WoW-Yapper's Lua engine.

    Lua's string.byte iterates over the bytes of a UTF-8 string, while Python
    iterates over Unicode code points. Encode before hashing so German
    characters such as ä, ö, ü, and ß produce matching hashes.
    """
    hash_val = 5381
    for byte in word.encode("utf-8"):
        # hash = (hash * 33 + c) mod 2^32
        hash_val = ((hash_val * 33) + byte) % 4294967296
    return hash_val

_LEET_MAP = str.maketrans({"0": "o", "1": "i", "3": "e", "4": "a",
                           "5": "s", "7": "t", "$": "s", "!": "i", "+": "t"})

def deleet(word):
    """Mirror of Utils.Deleet (Src/Utils.lua)."""
    return word.translate(_LEET_MAP)

def ascii_lower(word):
    """Mirror of the engine's NormaliseWord: Lua string.lower is ASCII-only,
    so 'ÄPFEL' -> 'Äpfel', NOT 'äpfel'."""
    return "".join(chr(ord(c) + 32) if "A" <= c <= "Z" else c for c in word)

def alpha_only(word):
    # Fuzzy normalizer: strips punctuation/digits to catch "dune-coon"-style
    # evasion when the user types it unpunctuated.
    return "".join(c for c in word if c.isalpha())

def surfaces(raw):
    """All word forms that can collide with a runtime hash. The runtime
    checks hash(NormaliseWord(typed)) and hash(Deleet(NormaliseWord(typed))),
    so emit the engine-surface, the unicode-lowered list surface, their
    alpha-stripped forms, and their deleeted forms."""
    out = set()
    for lower in {ascii_lower(raw.strip()), raw.strip().lower()}:
        if not lower:
            continue
        for s in {lower, alpha_only(lower), deleet(lower), deleet(alpha_only(lower))}:
            if s:
                out.add(s)
    return out

def process_file(filepath):
    words = set()
    path = Path(filepath)
    if not path.exists():
        print(f"Error: File '{filepath}' not found.")
        sys.exit(1)

    def add(raw):
        words.update(surfaces(raw))

    with open(path, 'r', encoding='utf-8') as f:
        # Check if it's a CSV
        if path.suffix.lower() == '.csv':
            reader = csv.reader(f)
            for row in reader:
                for col in row:
                    add(col)
        else:
            # Assume text file, one word per line
            for line in f:
                add(line)

    return sorted(list(words))

def main():
    parser = argparse.ArgumentParser(description="Generate Yapper blocked hashes from a list of bad words.")
    parser.add_argument("input", help="Input CSV or TXT file containing bad words.")
    args = parser.parse_args()

    words = process_file(args.input)
    if not words:
        print("No valid words found in input.")
        sys.exit(1)

    print("-- ---------------------------------------------------------------------------")
    print("-- Blocked words hashes (DJB2)")
    print("-- Generated by tools/generate_blocklist.py")
    print("-- ---------------------------------------------------------------------------")
    print("local BLOCKED_HASHES = {")
    
    # We output them sorted by word to make diffs cleaner if words are added,
    # but we only emit the hash to keep the word hidden.
    # To prevent easy reversing, we could shuffle them, but a set lookup in Lua doesn't care about order.
    # We will shuffle them to obscure alphabetical grouping.
    import random
    hashes = [djb2_hash(w) for w in words]
    random.shuffle(hashes)
    
    # Print in columns
    col = 0
    line = "    "
    for h in hashes:
        chunk = f"[{h}] = true, "
        if len(line) + len(chunk) > 80:
            print(line)
            line = "    " + chunk
        else:
            line += chunk
            
    if line.strip():
        print(line)
        
    print("}")
    print("\n-- Copy BLOCKED_HASHES into the target language engine.")

if __name__ == "__main__":
    main()
