#!/usr/bin/env python3
import sys
import csv
import argparse
from pathlib import Path

def djb2_hash(word):
    """
    Computes a 32-bit DJB2 hash of the word.
    Matches the exact implementation in WoW-Yapper's Lua engine.
    """
    hash_val = 5381
    for char in word:
        # hash = (hash * 33 + c) mod 2^32
        hash_val = ((hash_val * 33) + ord(char)) % 4294967296
    return hash_val

def normalize_word(word):
    # Match the Lua normalizer: lowercase and strip punctuation/spaces
    word = word.lower().strip()
    return "".join(c for c in word if c.isalpha())

def process_file(filepath):
    words = set()
    path = Path(filepath)
    if not path.exists():
        print(f"Error: File '{filepath}' not found.")
        sys.exit(1)
        
    with open(path, 'r', encoding='utf-8') as f:
        # Check if it's a CSV
        if path.suffix.lower() == '.csv':
            reader = csv.reader(f)
            for row in reader:
                for col in row:
                    w = normalize_word(col)
                    if w:
                        words.add(w)
        else:
            # Assume text file, one word per line
            for line in f:
                w = normalize_word(line)
                if w:
                    words.add(w)
                    
    return sorted(list(words))

def main():
    parser = argparse.ArgumentParser(description="Generate Yapper blocked hashes from a list of bad words.")
    parser.add_argument("input", help="Input CSV or TXT file containing bad words.")
    args = parser.parse_args()

    words = process_file(args.input)
    if not words:
        print("No valid words found in input.")
        sys.exit(1)

    print("-- ---------------------------------------------------------------------------")
    print("-- Blocked words hashes (DJB2)")
    print("-- Generated by tools/generate_blocklist.py")
    print("-- ---------------------------------------------------------------------------")
    print("local BLOCKED_HASHES = {")
    
    # We output them sorted by word to make diffs cleaner if words are added,
    # but we only emit the hash to keep the word hidden.
    # To prevent easy reversing, we could shuffle them, but a set lookup in Lua doesn't care about order.
    # We will shuffle them to obscure alphabetical grouping.
    import random
    hashes = [djb2_hash(w) for w in words]
    random.shuffle(hashes)
    
    # Print in columns
    col = 0
    line = "    "
    for h in hashes:
        chunk = f"[{h}] = true, "
        if len(line) + len(chunk) > 80:
            print(line)
            line = "    " + chunk
        else:
            line += chunk
            
    if line.strip():
        print(line)
        
    print("}")
    print("\n-- Remember to copy this into Dictionaries/Yapper_Dict_en/Engine.lua")

if __name__ == "__main__":
    main()
